config/routes.rb
Rails.application.routes.draw do
  resources :collections

  get   '/' => 'manifests#search'
  get   '/search' => 'manifests#search'
  get   '/searchresults' => 'manifests#searchresults'
  get   'advancedsearch' => 'manifests#advancedsearch'
  get   '/manifests/addcollection' => 'manifests#addcollection'
  get   '/collection/new'
  resources :manifests
  get   '/advanced_search' => 'manifests#advanced_search', :as => "advanced_search"
  get   '/list_logs' => 'log_files#list_logs', :as => "list_logs"
  get   '/log_files/:logfile', to: 'log_files#show', :as => "logfile"
  get   'addedcollection' => 'manifests#addedcollection'
  
  get   'api/v0.0/search/:query' => 'manifests#api_search', :as => "api_search"

end

app/models/collection.rb
class Collection
  include Elasticsearch::Persistence::Model

  attribute :collection_id, String
  attribute :index_started, DateTime
  attribute :index_finished, DateTime
  

  mapping do
    indexes :collection_id, :index => :uax_url_email
  end

  def self.find_by_at_id(at_id)
    definition = Elasticsearch::DSL::Search.search do 
      query do 
        term collection_id: at_id
      end
    end
    Collection.search(definition.to_hash).first
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
#      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:collection_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :collection_id %><br>
    <%= f.text_field :collection_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1>Listing collections</h1>

<table>
  <thead>
    <tr>
      <th>Collection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.collection_id %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<%= render "navbar" %>
<div id="main-container" class="container">

  <div class="row">
    <div class="col-md-8">
      <div class="field form-group form-inline">
        <h3>Submit a New Collection</h3>
        <p class="form-control-static">
          We index all the collections that are in the IIIF Universe file.  Collections outside of that can be indexed by entering them (once) here.
          You can also force indexing of your collection in Pontiiif by entering it here.
        </p>
        <%= form_tag({controller: 'manifests', action:'addcollection'}, method: 'get') do %>
          <div class="form-group">
            <%= label_tag :collection_id %>
            <%= text_field_tag :collection, params[:collection_id] %>
          </div>
          <%= submit_tag "Add", class: 'btn btn-default'  %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="field form-group form-inline">
        <p>Collections being indexed</p>
        <table class='table'>
          <thead>
            <tr>
              <td>
                ID
              </td>
              <td>
                Started
              </td>
              <td>
                Ended
              </td>
            </tr>
          </thead>
          <tbody>
            <% Collection.all.each do |collection| %>
              <tr>
                <td>
                  <%= collection.collection_id%>
                </td>
                <td>
                  <%= collection.index_started %>
                </td>
                <td>
                  <%= collection.index_finished %>
                </td>
              </tr>
            
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Collection:</strong>
  <%= @collection.collection_id %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>