config/routes.rb
Rails.application.routes.draw do
  resources :collections

  get   '/' => 'manifests#search'
  get   '/search' => 'manifests#search'
  get   '/searchresults' => 'manifests#searchresults'
  get   'advancedsearch' => 'manifests#advancedsearch'
  get   '/manifests/addcollection' => 'manifests#addcollection'
  get   '/collection/new'
  resources :manifests
  get   '/advanced_search' => 'manifests#advanced_search', :as => "advanced_search"
  get   '/list_logs' => 'log_files#list_logs', :as => "list_logs"
  get   '/log_files/:logfile', to: 'log_files#show', :as => "logfile"
  get   'addedcollection' => 'manifests#addedcollection'
  
  get   'api/v0.0/search/:query' => 'manifests#api_search', :as => "api_search"

end

app/models/manifest.rb
class Manifest
  include Elasticsearch::Persistence::Model

  attribute :manifest_id, String
  attribute :label,       String
  attribute :description, String
  attribute :raw_license,     String
  attribute :license,     String
   attribute :raw_license2, String
  attribute :raw_license3, String
  attribute :nav_date,     Date
  attribute :last_indexed_date, Date
  attribute :metadata, String
  attribute :domain, String
  attribute :thumbnail, String

  # The ActiveRecord pattern for the ElasticSearch Persistence gem doesn't automatically manage indexes


end

app/controllers/manifests_controller.rb
require 'elasticsearch/dsl'
require 'crawler_helper'

class ManifestsController < ApplicationController
  include Elasticsearch::DSL
  #before_action :set_manifest, only: [:show, :edit, :update, :destroy]

  # GET /manifests
  # GET /manifests.json
  def index
    @manifests = Manifest.all
  end

  # GET /manifests/1
  # GET /manifests/1.json
  def show
  end

  # GET /manifests/new
  def new
    @manifest = Manifest.new
  end

  # GET /manifests/1/edit
  def edit
  end

    #GET /manifests/search
   def search
     render action: "search"
   end

  def addcollection
    collection_id = params[:collection]
    collection = Collection.find_by_at_id(collection_id)
    unless collection
      Collection.create(:collection_id => collection_id)
    end

    rake_call = "rake pontiiif:ingest_collection[" + params[:collection] +"]  --trace 2>&1 >> rake_log.log &"
    logger.info rake_call
    system(rake_call)
    render action: "addedcollection"
  end

  def advanced_search
    query = {size: 0, aggs: {licenses: {terms: { field: "license" }}}}
    @query_results = Manifest.search(query)
    @licenses = @query_results.response["aggregations"]["licenses"]["buckets"].map { |h| h["key"] }
  end

  def advancedsearch
    must_array=[]
    if !params["label"].blank? then 
      label_match = {match: {label: params["label"]}} 
      must_array << label_match 
    end
    if !params["description"].blank? then 
      description_match = {match: {description: params["description"]}} 
      must_array << description_match
    end
    # if just a startDate, treat it as starting on jan 1 and going through the year
    # if just an endDate, same
    # if both...
    if !params["startDate"].blank? && !params["endDate"].blank? then
      startTime = Time.new(params["startDate"]).utc
      endTime = Time.new(params["endDate"]).utc
      endTime=endTime+1.year
      date_range = {range: {nav_date: {gte: startTime, lte: endTime}}} 
      must_array << date_range
    end
    #startDate no endDate
    if !params["startDate"].blank? && params["endDate"].blank? then
      startTime = Time.new(params["startDate"]).utc
      date_range = {range: {nav_date: {gte: startTime}}} 
      must_array << date_range
    end
    #endDate no startDate
    if params["startDate"].blank? && !params["endDate"].blank? then
      endTime = Time.new(params["endDate"]).utc
      endTime=endTime+1.year
      date_range = {range: {nav_date: {lte: endTime}}} 
      must_array << date_range
    end
    if !params["metadata"].blank? then 
      metadata_match = {match: {metadata: params["metadata"]}} 
      must_array << metadata_match
    end
    if !params["license"]["license_id"].blank? then 
      license_match = {match: {license: params["license"]["license_id"]}} 
      must_array << license_match
    end
    bool_clause = {bool: {must: must_array}}
    query = {query: bool_clause}
    @manifests = Manifest.search(query)
    render action: "index"
  end

  # GET /manifests/search
  def searchresults
    @manifests = Manifest.search(params[:q])
    render action: "index"
  end

  # POST /manifests
  # POST /manifests.json
  def create
    @manifest = Manifest.new(manifest_params)

    respond_to do |format|
      if @manifest.save
        format.html { redirect_to @manifest, notice: 'Manifest was successfully created.' }
        format.json { render :show, status: :created, location: @manifest }
      else
        format.html { render :new }
        format.json { render json: @manifest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manifests/1
  # PATCH/PUT /manifests/1.json
  def update
    respond_to do |format|
      if @manifest.update(manifest_params)
        format.html { redirect_to @manifest, notice: 'Manifest was successfully updated.' }
        format.json { render :show, status: :ok, location: @manifest }
      else
        format.html { render :edit }
        format.json { render json: @manifest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manifests/1
  # DELETE /manifests/1.json
  def destroy
    @manifest.destroy
    respond_to do |format|
      format.html { redirect_to manifests_url, notice: 'Manifest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def api_search
    @manifests = Manifest.search(params[:query])
    collection = IIIF::Presentation::Collection.new
    collection['@id'] = api_search_path({:query => params[:query], :only_path => false})
    collection.label = "IIIF resources discovered by searching the Pontiiif installation at for '#{params[:query]}' at #{Time.now}"
    
    @manifests.each do |db_manifest|
      seed = { 
        '@id' => db_manifest.manifest_id, 
        'label' => db_manifest.label,
        'description' => db_manifest.description
      }
      manifest = IIIF::Presentation::Manifest.new(seed)
      manifest.metadata = db_manifest.metadata if db_manifest.metadata
      manifest.thumbnail = db_manifest.thumbnail if db_manifest.thumbnail  
      manifest.license = db_manifest.license if db_manifest.license
      
      collection.manifests << manifest 
    end

    render :text => collection.to_json(pretty: true), :content_type => "application/json"

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manifest
      @manifest = Manifest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manifest_params
      params.require(:manifest).permit(:manifest_id, :label, :description, :license, :nav_date)
    end
end

app/helpers/manifests_helper.rb
module ManifestsHelper
end

app/views/manifests/_form.html.erb
<%= form_for(@manifest) do |f| %>
  <% if @manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manifest.errors.count, "error") %> prohibited this manifest from being saved:</h2>

      <ul>
      <% @manifest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manifest_id %><br>
    <%= f.text_field :manifest_id %>
  </div>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :license %><br>
    <%= f.text_field :license %>
  </div>
  <div class="field">
    <%= f.label :nav_date %><br>
    <%= f.text_field :nav_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manifests/addedcollection.html.erb
<%= render "navbar" %>
<div id="main-container" class="container">

<div class="row">
<div class="col-md-8">
<h3>Your collection has been added.</h3>
<p>Consider adding it to <a href="https://github.com/ryanfb/iiif-universe/blob/gh-pages/iiif-universe.json">https://github.com/ryanfb/iiif-universe/blob/gh-pages/iiif-universe.json</a> so that it will be reindexed automatically.</p>
 </div>
  </div>
  </div>

app/views/manifests/advanced_search.html.erb
<%= render "navbar" %>
<div id="main-container" class="container">

<div class="row">
<div class="col-md-8">
<div class="field form-group">
<h3>Advanced Search</h3>

  <%= form_tag 'advancedsearch', method: 'get' do %>
    <div class="form-group">
    <%= label_tag :label %>
    <%= text_field_tag :label, params[:label], class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= label_tag :description %>
    <%= text_field_tag :description, params[:description], class: 'form-control' %>
        </div>
    <div class="form-group">
    <%= label_tag :metadata %>
    <%= text_field_tag :metadata, params[:metadata], class: 'form-control' %>
        </div>
    <div class="form-group">
    <%= label_tag :license %>
    <%= collection_select(:license, :license_id, @licenses, :to_s, :to_s, include_blank: true, class: 'form-control') %>
    </div>
    <div class="form-group">
    <%= label_tag :start_Year %>
    <%= text_field_tag :startDate, params[:startDate], placeholder: "1800 or +1800 or -300 or blank", class: 'form-control' %>
        </div>
    <div class="form-group">
    <%= label_tag :end_Year %>
    <%= text_field_tag :endDate, params[:endDate], placeholder: "1800 or +1800 or -300 or blank", class: 'form-control' %>
        </div>
    <%= submit_tag :advancedsearch , class: 'btn btn-default' %>
  <% end %>
  </div>
  </div>
  </div>
  </div>

app/views/manifests/edit.html.erb
<h1>Editing manifest</h1>

<%= render 'form' %>

<%= link_to 'Show', @manifest %> |
<%= link_to 'Back', manifests_path %>

app/views/manifests/index.html.erb
<%= render "navbar" %>
<div id="main-container" class="container">

    <hgroup class="mb20">
    <h1>Search Results</h1>
    <% if @manifests.count == 1 %>
    <h2 class="lead"><strong class="text-danger"><%= @manifests.count %></strong> result was found.</h2>
    <% elsif @manifests.count == 0 %>
        <h2 class="lead"><strong class="text-danger">No results found.</h2>
    <% else %>    
    <h2 class="lead"><strong class="text-danger"><%= @manifests.count %></strong> results were found.</h2>   
    <% end %>            
  </hgroup>

    <section class="col-xs-12 col-sm-6 col-md-12">
   <% @manifests.each do |manifest| %>   
    <article class="search-result row">
      <div class="col-xs-12 col-sm-12 col-md-2">
      </div>
      <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
        <h3><a href="http://universalviewer.io/examples/?manifest=<%= manifest.manifest_id %>" title=""><%= manifest.label %></a></h3>
        <% if manifest.description %>
          <p>        <% manifest.description.each do |description_hash| %>
            <%= raw(description_hash["value"]) %> <br>
         <% end %>
         </p>  
         <% end %>
        <p><%= manifest.license %></p>       
                <a target=”_blank” href="http://universalviewer.io/examples/?manifest=<%= manifest.manifest_id %>">
            <%= image_tag 'logo-iiif.png', :alt => 'Drag onto an IIIF client or click to open in Universal Viewer'%>
          </a>
          <%= link_to manifest.manifest_id, manifest.manifest_id %>
      </div>
      <span class="clearfix borda"></span>
    </article>
    <% end %>

  
<br>

</div>

app/views/manifests/new.html.erb
<h1>New manifest</h1>

<%= render 'form' %>

<%= link_to 'Back', manifests_path %>

app/views/manifests/search.html.erb
<%= render "navbar" %>

<div id="main-container" class="container">

      <div class="row">
      <div class="col-md-8">
<h1>Search manifests</h1>

<div class="field form-group">
  <%= form_tag searchresults_path, class: 'form-horizontal', method: 'get' do %>
    <div class="col-sm-10">
      <%= text_field_tag :q, params[:q], placeholder: "Bronte or purple or Bronte purple", class: 'form-control' %>
      <%= submit_tag :searchresults, class: 'btn btn-primary' %>
      </div>
  <% end %>

</div>
</div>
</div>

<!--
<div class="row">
<div class="col-md-8">
<div class="field form-group">
<h3>Advanced Search</h3>

  <%= form_tag 'advancedsearch', method: 'get' do %>
    <div class="form-group">
    <%= label_tag :label %>
    <%= text_field_tag :label, params[:label], class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= label_tag :description %>
    <%= text_field_tag :description, params[:description], class: 'form-control' %>
        </div>
    <div class="form-group">
    <%= label_tag :metadata %>
    <%= text_field_tag :metadata, params[:metadata], class: 'form-control' %>
        </div>
    <div class="form-group">    
    <%= label_tag :license %>
    <%= text_field_tag :license, params[:license], class: 'form-control' %>
        </div>
    <div class="form-group">
    <%= label_tag :start_Date %>
    <%= text_field_tag :startDate, params[:startDate], class: 'form-control' %>
        </div>
    <div class="form-group">
    <%= label_tag :end_Date %>
    <%= text_field_tag :endDate, params[:endDate], class: 'form-control' %>
        </div>
    <%= submit_tag :advancedsearch , class: 'btn btn-default' %>
  <% end %>
  </div>
  </div>
  </div>

      <div class="row">
      <div class="col-md-8">
<div class="field form-group form-inline">
  <h3>Submit a New Collection</h3>
   <p class="form-control-static">We index all the collections that are in the IIIF Universe file.  Collections outside of that can be indexed by entering them (once) here.
  You can also force indexing of your collection in Pontiiif by entering it here.</p>
  <%= form_tag 'manifests/addcollection', method: 'get' do %>
    <div class="form-group">
    <%= label_tag :collection_id %>
    <%= text_field_tag :collection, params[:collection_id] %>
    </div>
    <%= submit_tag :addcollection, class: 'btn btn-default'  %>
  <% end %>
  </div>
  </div>
  </div>
  -->


  </div>

  <%= render "footer" %>

app/views/manifests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manifest:</strong>
  <%= @manifest.manifest_id %>
</p>

<p>
  <strong>Label:</strong>
  <%= @manifest.label %>
</p>

<p>
  <strong>Description:</strong>
  <%= @manifest.description %>
</p>

<p>
  <strong>License:</strong>
  <%= @manifest.license %>
</p>

<p>
  <strong>Navdate:</strong>
  <%= @manifest.nav_date %>
</p>

<%= link_to 'Edit', edit_manifest_path(@manifest) %> |
<%= link_to 'Back', manifests_path %>