config/routes.rb
Rails.application.routes.draw do
  resources :collections

  get   '/' => 'manifests#search'
  get   '/search' => 'manifests#search'
  get   '/searchresults' => 'manifests#searchresults'
  get   'advancedsearch' => 'manifests#advancedsearch'
  get   '/manifests/addcollection' => 'manifests#addcollection'
  get   '/collection/new'
  resources :manifests
  get   '/advanced_search' => 'manifests#advanced_search', :as => "advanced_search"
  get   '/list_logs' => 'log_files#list_logs', :as => "list_logs"
  get   '/log_files/:logfile', to: 'log_files#show', :as => "logfile"
  get   'addedcollection' => 'manifests#addedcollection'
  
  get   'api/v0.0/search/:query' => 'manifests#api_search', :as => "api_search"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<hr>
<p class="text-center"><small>A project of <a href="http://www.brumfieldlabs.com">Brumfield Labs</a></small></p>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
  	  <%= image_tag("WinchesterBibleP.jpg", alt: "Illuminated P", class: "navbar-brand") %>	
      <%= link_to "Pontiiif", search_path, class: "navbar-brand" %>
      <%= link_to "Advanced Search|", advanced_search_path, class: "navbar-nav" %>
      <%= link_to "Add a Collection|", new_collection_path, class: "navbar-nav" %>
      <%= link_to "View Log Files", list_logs_path, class: "navbar-nav" %>
  </div>
</nav>